### ISSUE TITLE
根据教程走，最后一步报错

### ISSUE THREAD

**Issue by Xiaye2332** [lixiang810/totoroschool-autorun#6]
```
[root@VM-16-8-centos totoroschool-autorun-main]# yarn start

Internal Error: fk-totoro-exp@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at tF.getCandidates (/home/admin/totoroschool-autorun-main/.yarn/releases/yarn-3.2.0.cjs:437:4480)
    at wd.getCandidates (/home/admin/totoroschool-autorun-main/.yarn/releases/yarn-3.2.0.cjs:395:1281)
    at /home/admin/totoroschool-autorun-main/.yarn/releases/yarn-3.2.0.cjs:441:7765
    at Pg (/home/admin/totoroschool-autorun-main/.yarn/releases/yarn-3.2.0.cjs:394:11098)
    at le (/home/admin/totoroschool-autorun-main/.yarn/releases/yarn-3.2.0.cjs:441:7745)
```

以上是报错内容

**Comment by Xiaye2332** [comment]
即使执行`yarn install`依然出现同样报错

**Comment by lixiang810** [comment]
注意到系统是centos 16.8，这是一个很旧的系统。你的 node 版本是多少？

**Comment by Xiaye2332** [comment]
16.17.0

**Comment by lixiang810** [comment]
那试着输这个：`corepack enable`，之后重复上面的操作

**Comment by Xiaye2332** [comment]
提示无此命令`-bash: corepack: command not found`

**Comment by lixiang810** [comment]
你有docker环境吗？我可以考虑打包一个docker上来。

**Comment by Xiaye2332** [comment]
目前还没有，这个系统只是测试使用，如果可以的话我想用Ubuntu再尝试一下，请问版本应当选择什么？

**Comment by lixiang810** [comment]
node 16的最新版本就行了。corepack 应该是随着 node 一起装上的才对，不知道为啥你这里没有。你是咋装的？

**Comment by Xiaye2332** [comment]
使用的Yum

**Comment by lixiang810** [comment]
可以试试卸了之后用 [nvm](https://github.com/nvm-sh/nvm) 安装

**Comment by Xiaye2332** [comment]
尝试使用了 nvm ，一次安装成功，看来使用CentOS自带的Yum会存在一些BUG
